### ISSUE TITLE
Compiled package for windows

### ISSUE THREAD

**Issue by GHNewbiee** [pjungwir/inetrange#2]
Hi Paul,

If you have already compiled the extension in **windows** env, I would appreciate to give us an official link for downloading or instructions which packages/tools you used.

Tia

**Comment by pjungwir** [comment]
Hi @GHNewbiee,

I'm glad to see that this extension is useful to someone! I don't have any experience compiling it on Windows, but it sounds like the instructions [on the wiki](https://wiki.postgresql.org/wiki/Building_and_Installing_PostgreSQL_Extension_Modules) might be helpful. If you get it working I'd love to add some instructions to the README. Keep me posted how it goes!

Thanks,
Paul

**Comment by GHNewbiee** [comment]
Hi, I have managed to run `make` and create the `inetrange.dll` file but `make install` failed. So, I just copied manually the files to the appropriate directories. I used MinGW and not Visual Studio.

[inetrange-1.0.0.zip](https://github.com/pjungwir/inetrange/files/1604423/inetrange-1.0.0.zip)

Rgrds

PS: dll file is 64-bit.
